# Site settings
title: Adam Gordon
email: ag@adamgordon.ca
description: > # this means to ignore newlines until "baseurl:"
  Adam Gordon's personal homepage
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://adamgordon.ca" # the base hostname & protocol for your site
twitter_username: ca_adamgordon
github_username:  gordon-to

# Build settings
markdown: kramdown

# Enable plugins
plugins_dir: _plugins

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
